---
- hosts: all
  sudo: yes
  vars:
     # php5-fpm
     max_children: 10
     start_servers: 2
     min_spare_servers: 1
     max_spare_servers: 3
  tasks:
    - include: tasks/nginx.yml

    - name: Make entrypoint for docker container
      copy: src=files/container-run.sh dest=/usr/local/bin/container-run.sh mode=0755 owner=root group=root

  handlers:
    - include: handlers/nginx.yml
